image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test-build:
    before_script:
        - export DEBIAN_FRONTEND=noninteractive
        - apt-get -yq update && apt-get -y install g++ cmake libprotobuf-dev libboost-all-dev libasio-dev
    script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .

check-formatting:
    before_script:
        - export DEBIAN_FRONTEND=noninteractive
        - apt-get -yq update && apt-get -y install clang-format
    script:
        - find src include apps \( -iname *.hpp -o -iname *.cpp \) | xargs clang-format -style=file -n -Werror
