image: jsangmeister/spanners-base:latest

variables:
    GIT_SUBMODULE_STRATEGY: recursive

test-build:
    script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .

check-formatting:
    script:
        - find src include apps \( -iname *.hpp -o -iname *.cpp \) | xargs clang-format -style=file -n -Werror
