version: "3.6"

services:
  backend:
    build: .
    ports:
      - "4711:4711"
    working_dir: /opt/backend/build
    command: bash -c "cmake -DUNENCRYPTED_CONNECTION=ON .. && make -j$$(nproc) && ./apps/server" # disable TLS encryption
    environment:
      SPANNERS_SERVER_PORT: 4711
      SPANNERS_DB_HOST: postgres
      SPANNERS_DB_NAME: spanner_db
      SPANNERS_DB_USER: spanner_user
      SPANNERS_DB_PASSWORD: pwd
    volumes:
      - ./:/opt/backend

  postgres:
    image: postgres:13.5
    environment:
      POSTGRES_DB: spanner_db
      POSTGRES_USER: spanner_user
      POSTGRES_PASSWORD: pwd
    volumes:
      - ./:/opt/backend